<?php

/*
 * Form functions for "Step 3: Moderate LWCs - Split node"
 */

//module_load_include('inc', 'living_word_admin', 'living_word_admin.form');
//module_load_include('inc', 'node', 'node.admin');
//module_load_include('inc', 'living_word_admin', 'living_word_admin.add.form');


/**
 * Form builder
 * Much of this is shamelessly copied from node.admin.inc
 */
function living_word_admin_split_form($form, &$form_state) {

  $bundle = 'living_word_comment';



  return $form;

}

