<?php

module_load_include('inc','scripture','scripture.field');
module_load_include('inc','scripture','scripture.db');

/**
 * Implements hook_permission().
 */
function scripture_permission() {
  $permissions = array();
  
  $permissions['scripture_admin'] = array(
    'title' => t('Scripture admin'), 
    'description' => t('Administer translations and subverses of the Scripture module'),
  ),
   
  return $permissions;
}

/**
 * Implements hook_menu().
 * https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_menu/7
 */
function scripture_menu() {
  $items = array();
  
  $items['admin/structure/scripture'] = array(
    'title'            => 'Scripture',
    'type'             => MENU_NORMAL_ITEM,
    'description'      => 'Manage the Scripture module',
    'page callback'    => 'scripture_callback_status',
    'access callback'  => 'user_access',
    'access arguments' => array('scripture_admin'),
    'file'             => 'scripture.admin.inc',
  );
  
  $items['admin/structure/scripture/status'] = array(
    'title'         => 'Status',
    'description'   => 'View status and statistics',
    'type'          => MENU_DEFAULT_LOCAL_TASK,
    'weight'        => 10,
    'page callback' => 'scripture_callback_status',
    'file'          => 'scripture.admin.inc',
  );
  
  $items['admin/structure/scripture/translations'] = array(
    'title'         => 'Translations',
    'description'   => 'Manage installed translations',
    'type'          => MENU_LOCAL_TASK,
    'weight'        => 20,
    'page callback' => 'scripture_callback_translations',
    'file'          => 'scripture.admin.inc',
  );
  
  $items['admin/structure/scripture/subverses'] = array(
    'title'         => 'Subverses',
    'description'   => 'Manage subverses',
    'type'          => MENU_LOCAL_TASK,
    'weight'        => 30,
    'page callback' => 'scripture_callback_subverses',
    'file'          => 'scripture.admin.inc',
  );
  
  return $items;
}

