<?php

module_load_include('inc','scripture','scripture.field');
module_load_include('inc','scripture','scripture.db');
module_load_include('inc','scripture','scripture.element');

/**
 * Implements hook_permission().
 */
function scripture_permission() {
  $permissions = array();
  
  $permissions['scripture_admin'] = array(
    'title' => t('Scripture admin'),
    'description' => t('Administer translations and subverses of the Scripture module'),
  );
   
  return $permissions;
}

/**
 * Implements hook_menu().
 * https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_menu/7
 */
function scripture_menu() {
  $items = array();
  
  $items['admin/structure/scripture'] = array(
    'title'            => 'Scripture',
    'type'             => MENU_NORMAL_ITEM,
    'description'      => 'Manage the Scripture module',
    'page callback'    => 'scripture_callback_status',
    'access callback'  => 'user_access',
    'access arguments' => array('scripture_admin'),
    'file'             => 'scripture.admin.inc',
  );
  
  $items['admin/structure/scripture/status'] = array(
    'title'         => 'Status',
    'description'   => 'View status and statistics',
    'type'          => MENU_DEFAULT_LOCAL_TASK,
    'weight'        => 10,
    'page callback' => 'scripture_callback_status',
    'access callback'  => 'user_access',
    'access arguments' => array('scripture_admin'),
    'file'          => 'scripture.admin.inc',
  );
  
  $items['admin/structure/scripture/translations'] = array(
    'title'            => 'Translations',
    'description'      => 'Manage installed translations',
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 20,
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('scripture_callback_translations'),
    'access callback'  => 'user_access',
    'access arguments' => array('scripture_admin'),
    'file'             => 'scripture.admin.inc',
  );
  
  $items['admin/structure/scripture/subverses'] = array(
    'title'            => 'Subverses',
    'description'      => 'Manage subverses',
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 30,
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('scripture_callback_subverses'),
    'access callback'  => 'user_access',
    'access arguments' => array('scripture_admin'),
    'file'             => 'scripture.admin.inc',
  );
  
  return $items;
}

/**
 * Implements hook_element_info().
 * https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_element_info/7
 * Declare a FORM API element for the verse picker
 */
function scripture_element_info() {
  return array(
    'scripture_verse_picker' => array(
      '#input'          => TRUE,
      '#process'        => array('scripture_verse_picker_process'),
      '#theme'          => array('scripture_verse_picker'),
      '#theme_wrappers' => array('form_element'),
      '#tree'           => TRUE,
    ),
  );
}

/**
 * Implements hook_theme($existing, $type, $theme, $path).
 * https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_theme/7
 * Registers the module's theme implementations
 */
function scripture_theme($existing, $type, $theme, $path) {
  return array(
    'scripture_verse_picker' => array(
      'render element' => 'element',
    ),
  );
}

