<?php

module_load_include('inc','living_word','living_word.node');


/**
 * Define listing order options
 */

define('LIVING_WORD_LISTING_ORDER_PREDOMINANT_MULTI_VERSE', 0x0001);
define('LIVING_WORD_LISTING_ORDER_SINGLE_SUB_VERSE', 0x0002);
define('LIVING_WORD_LISTING_ORDER_APPLICATION_TAGS', 0x0003);


/**
 * Query the database for living word comment nodes based on conditions
 */
function living_word_get_comments($picker_values = array(), $detail_values = array(), $position_values = array()) {
  
}


/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter(&$element, &$form_state, $context).
 * https://api.drupal.org/api/drupal/modules!field!field.api.php/function/hook_field_widget_WIDGET_TYPE_form_alter/7
 * Specify the source text for the JS field widget, from which the quoted text
 * must be selected.
 */
function living_word_field_widget_living_word_quote_widget_js_form_alter(&$element, &$form_state, $context) {
  $element['#source_text'] = t("The Word is alive");
  // TODO: get the verse range associated with the node, etc.
}

