<?php

module_load_include('inc','living_word','living_word.node');


/**
 * Define listing order options
 */

define('LIVING_WORD_LISTING_BEHAVIOUR_BROAD', 0x0001);
define('LIVING_WORD_LISTING_BEHAVIOUR_NARROW', 0x0002);
define('LIVING_WORD_LISTING_BEHAVIOUR_TOPICAL', 0x0003);


/**
 * Query the database for living word comment nodes based on conditions
 */
function living_word_get_comments($picker_values = array(), $detail_values = array(), $position_values = array()) {
  
}

